channels:
- conda-forge
dependencies:
- python=3.9.5
- pip<=21.2.4
- pip:
  - mlflow<3,>=2.3
  - azureml-mlflow==1.50.0
  - boto3==1.21.18
  - cloudpickle==2.2.1
  - datascience-core==2.0
  - docker==6.0.1
  - ipywidgets==7.7.0
  - matplotlib==3.4.3
  - numpy==1.22.4
  - packaging==21.0
  - pandas==1.3.4
  - protobuf==4.22.3
  - pytz==2021.3
  - pyyaml==6.0
  - requests==2.26.0
  - scikit-learn==0.24.2
  - scipy==1.7.1
  - statsmodels==0.12.2
name: mlflow-env
