name: PyTest
on:
  pull_request:
    branches:
      - main
env:
  AZURE_APP_CONFIG_CONNECTION_STRING: ${{ secrets.AZURE_APP_CONFIG_CONNECTION_STRING }}
  AZURE_ENVIRONMENT_NAME: ${{ secrets.AZURE_ENVIRONMENT_NAME }}
  AZURE_DATA_LAKE: ${{ secrets.AZURE_DATA_LAKE }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
  AZURE_ML_WORKSPACE: ${{ secrets.AZURE_ML_WORKSPACE }}

jobs:
  test:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 9

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Microsoft ODBC
        run: sudo ACCEPT_EULA=Y apt-get install msodbcsql17 -y
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          

      - name: Run test suite
        run: |
          pytest datadayessentials 
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build using pip
        run: |
          pip install wheel
          pip install git+https://github.com/data-day-science/datadayessentials@${{ steps.extract_branch.outputs.branch }}#egg=datadayessentials
      - name: Post build tests
        run: |
          python -c "from datadayessentials.authentications import DataLakeAuthentication"
        shell: sh
