name: DeployDocs 
on: workflow_dispatch
  # push:
  #   branches:
  #     - main
    # inputs:
    #   deploy_environment:
    #     description: 'choose the environment to deploy to'
    #     required: true
    #     default: 'dev'
jobs:
  build:
    env:
      AZURE_WEBAPP_NAME: ds-core-docs
    runs-on: 'ubuntu-latest'
    timeout-minutes: 9

    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
 
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install pdoc 
        run: |
          pip install pdoc
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Generate the docs
        run: |
          pdoc ./datascience_core -o /tmp/docs

      - uses: actions/upload-pages-artifact@v1
        with:
          path: /tmp/docs/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2