name: DeployDocs 
on:
  workflow-dispatch:
  # push:
  #   branches:
  #     - main
    # inputs:
    #   deploy_environment:
    #     description: 'choose the environment to deploy to'
    #     required: true
    #     default: 'dev'
jobs:
  deploy_docs:
    env:
      AZURE_WEBAPP_NAME: ds-core-docs
    runs-on: ['ubuntu-latest']
    timeout-minutes: 9

    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
 
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install pdoc 
        run: |
          pip install pdoc
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Generate the docs
        run: |
          pdoc ./datascience_core -o /tmp/docs

